### ISSUE TITLE
Avro stops after typing few words in Bengali

### ISSUE THREAD

**Issue by Rafiquzzaman420** [sarim/ibus-avro#176] opened 2021-06-04 02:54 UTC

**Comment by apandada1** [comment] 2021-06-04 03:54
This is a known gjs bug (not an ibus-avro bug) that randomly affects some systems.
Duplicate of https://github.com/sarim/ibus-avro/issues/156

**Comment by Rafiquzzaman420** [comment] 2021-06-04 08:10
> This is a known gjs bug (not an ibus-avro bug) that randomly affects some systems.
> Duplicate of #156

Sorry brother I found the problem and it was my language pack. I updated it and applied all over the system and it is working as a charm now . Thanks for the reply though. :smiley:

**Closed** 2021-06-04 08:13 UTC

**Comment by apandada1** [comment] 2021-06-04 08:25
@Rafiquzzaman420 How exactly did you fix it? Please post it. It may help to solve the duplicate issues.

**Comment by Rafiquzzaman420** [comment] 2021-06-06 00:34
> > it was my language pack. I updated it and applied all over the system and it is working as a charm now
> 
> Was your locale possibly broken, and you somehow fixed that via Language Support?

Yes brother. I fixed it via the language support. I didn't updated my **Language Support** since the installation of Ubuntu. That's why when I found that my problem was in Language, I should check the **Language Support** & it did work. 
Hope you got your answer.

**Comment by gunnarhj** [comment] 2021-06-06 03:23
Ok. It's not clear to me how a broken locale could cause Avro to first work and then suddenly stop working.

Anyway, can you please show us what these commands output:

    locale

    echo $XDG_CURRENT_DESKTOP

    env | grep -E 'XMOD|_IM'

**Comment by Rafiquzzaman420** [comment] 2021-06-06 10:45
```
user@user:~$ locale

LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=en_US.UTF-8
LC_TIME=en_US.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=en_US.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_ADDRESS=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_ALL=
```

```
user@user:~$ echo $XDG_CURRENT_DESKTOP
ubuntu:GNOME
```

```
user@user:~$ env | grep -E 'XMOD|_IM'
XMODIFIERS=@im=ibus
QT_IM_MODULE=ibus
```

**Comment by gunnarhj** [comment] 2021-06-06 11:46
Thanks @Rafiquzzaman420. That looks quite normal. Can't help wondering what it looked like before you played with _Language Support_ though.

**Comment by Rafiquzzaman420** [comment] 2021-06-07 06:30
> Thanks @Rafiquzzaman420. That looks quite normal. Can't help wondering what it looked like before you played with _Language Support_ though.

Next time when I do this on my other PC, I'll let you know :)
