### ISSUE TITLE
ibus-avro possibly a Debian/Ubuntu package soon etc.

### ISSUE THREAD

**Issue by gunnarhj** [sarim/ibus-avro#128] opened 2019-07-25 04:43 UTC
Hi!

Would like to mention that I'm trying to get `ibus-avro` into the official Debian/Ubuntu archives. It's currently in Debian's NEW queue, and we are waiting for a decision by someone from the FTPMasters team:

https://ftp-master.debian.org/new/ibus-avro_1.0+git20170418-1.html

If approved my plan is to backport `ibus-avro` to Ubuntu 19.04, 18.04 and 16.04.

When preparing the package we identified an issue when Avro Phonetic is used on GNOME desktops on Xorg, which includes Ubuntu on Xorg (the default environment in 18.04 and 19.04). Advice how to deal with the issue will be provided to the users in a `README.Debian` file, and an extract from a draft of that file follows:
```
Heads-up for GNOME on Xorg (including Ubuntu on Xorg)
-----------------------------------------------------
Avro Phonetic is configured to use the English (US) keyboard layout.
If you have some other XKB layout but the basic English (US) layout
among the available input sources, it must not be the first source in
the list in a GNOME on Xorg session. If it is, using Avro Phonetic
will result in the latin letters being inputted instead of the
transliterated Bangla characters.

The simple advice is: Either Avro Phonetic or English (US) should be
the first source.

    An example:

    If the only input source you were using before installing ibus-avro
    was "English (UK)", and you add "Bangla (Avro Phonetic)", you may
    see this list of input sources in Settings -> Region & Language:

    * English (UK)
    * Bangla (Avro Phonetic)

    That won't work, and the simplest way to fix it in this case is to
    move "Bangla (Avro Phonetic)" to the top so the "Input Sources"
    list looks like this:

    * Bangla (Avro Phonetic)
    * English (UK)

Please note that US layout variants, e.g. "English (US, intl., with
dead keys)", do not qualify as "English (US)" in this respect. So if
you are using such a layout, the equivalent advice as for "English
(UK)" applies.
```
The GNOME on Xorg issue is present irrespective of how Avro Phonetic was installed, and the above extract may be what's needed to fix it for some users who have reported issues, for instance #123 and #124.

While the application to include `ibus-avro` officially in Debian/Ubuntu is being processed, I'm also making it available in this PPA:

https://launchpad.net/~gunnarhj/+archive/ubuntu/avro

**Comment by sarim** [comment] 2019-07-25 12:07
Nice initiative (y) bear in mind that current version of ibus-avro is in maintenance only mode (aka no feature update). v2.0 is being rewritten in golang which will replace this javascript version. 

About this gnome on xorg issue, i don't get it. For the use case of our users, input source is supposed to look like 

* English (US)
* Bangla (Avro Phonetic)

Users press the change input source hotkey [cntrl + space] or [meta + space] etc... to trigger input source to bangla, and write bangla. Then press the hotkey again to move input source back to english.

Also ibus-avro is just interfacing with ibus, not the xkb/xorg underneath. So i'm unclear how this is related to ibus-avro.

I have personally tested and ibus-avro in its current state, works in all DE (gnome, kde, lxde etc..) where ibus is supported. The issues reported here are mostly user error, among those are,

1. IBus is not properly configured in DE, ex: ibus gtk3/gtk2/qt immodule not installled, or GTK_IM_MODULE=ibus not set.
2. After installing ibus-avro, ibus daemon is not reloaded so ibus-avro is not showing up in input sources list. solution is to reload ibus-daemon manually or restart DE (gnome) session.

**Comment by gunnarhj** [comment] 2019-07-25 13:34
> Nice initiative (y)

I'm glad you are positive. And thanks for making Avro Phonetic available!

> bear in mind that current version of ibus-avro is in maintenance only mode (aka no feature update).

Yep, I'm aware of that. Still think it's good enough to be worth the effort to make it more easily available via the official archives.

> v2.0 is being rewritten in golang which will replace this javascript version.

Hopefully that will be just as easy to package in Debian as 1.0 is.

> About this gnome on xorg issue, i don't get it. For the use case of our users, input source is supposed to look like
> 
>     * English (US)
>     * Bangla (Avro Phonetic)

While that may be the most common use case, you can't be sure that it's true for all users of Avro Phonetic, can you? As an example I can imagine that this one exists:

- English (US, intl., with dead keys)
- Bangla (Avro Phonetic)

And with that order it doesn't work in a GNOME on Xorg environment. The workaround is trivial, obviously - if you know about it. Otherwise it can give an affected user a lot of headache.

> Also ibus-avro is just interfacing with ibus, not the xkb/xorg underneath. So i'm unclear how this is related to ibus-avro.

I have thought about 'whose fault' this can be. I have confirmed that the issue is not present in other desktop environments (including GNOME on Wayland), so that speaks for some kind of GNOME bug. OTOH, other IBus input methods such as ibus-libpinyin or ibus-mozc work fine also on GNOME on Xorg, and that speaks for it being possible to deal with by modifying ibus-avro.

But I didn't post here with the aim to ask you to fix it. The problem has been nailed down and there is a trivial workaround, so I'm simply trying to spread the word. If you can confirm my examples, maybe you want to mention something about it at this site. Please note that the default environment of Ubuntu 18.04 and 19.04 is just GNOME on Xorg. I'd suspect that these two problem reports to Ask Ubuntu are caused by the issue:

- [Avro is installed, but bangla writting is still not coming](https://askubuntu.com/questions/1077412/avro-is-installed-but-bangla-writting-is-still-not-coming)
- [IBus Avro is not working on Ubuntu 18.04](https://askubuntu.com/questions/1119150/ibus-avro-is-not-working-on-ubuntu-18-04)

> I have personally tested and ibus-avro in its current state, works in all DE (gnome, kde, lxde etc..) where ibus is supported. The issues reported here are mostly user error, among those are,
> 
>     1. IBus is not properly configured in DE, ex: ibus gtk3/gtk2/qt immodule not installled, or GTK_IM_MODULE=ibus not set.
> 
>     2. After installing ibus-avro, ibus daemon is not reloaded so ibus-avro is not showing up in input sources list. solution is to reload ibus-daemon manually or restart DE (gnome) session.

Right, I can confirm that ibus-avro seems to work fine everywhere, and agree that most problem reports seem to be user errors. The package I'm working with includes `ibus`, `ibus-gtk` and `ibus-gtk3` in the dependencies list to reduce the risk for the latter kind of problems. (It does not include `ibus-qt4`, though, since that package has been dropped from Debian/Ubuntu.)

**Comment by sarim** [comment] 2019-07-25 13:59
I see, i think now i understand the problem a bit better. I'll do a bit more research about this myself. In your linked threads i see you're suggesting to use `default` instead of `us` in layout. If you have tested this in various DE(s) in various version of distros and it works everywhere properly, And you feel confident it is the right solution, feel free to apply that as a patch in your packages :) 

> But I didn't post here with the aim to ask you to fix it. The problem has been nailed down and there is a trivial workaround, so I'm simply trying to spread the word. 

Hey no problem, Its better for me to know the problem so i can address it, if not in this version, then in the new one. Thank you for that. (y)

**Comment by gunnarhj** [comment] 2019-07-26 00:40
Thought I'd elaborate on how the "GNOME on Xorg" issue manifests itself if you set "default" instead of "us" in the XML file.

As long as you only have Avro Phonetic plus one XKB layout (basically any latin layout) it works fine. The latin layout you chose is the default, and Avro Phonetic uses it without issues.

But assume this list:

- English (US)
- English (UK)
- Bangla (Avro Phonetic)

English (US) is default, since it's at the top of the list. If you switch from English (US) to Avro Phonetic, it works, but if you switch from English (UK) directly to Avro Phonetic, only latin letters are inputted. And you can't fix it by changing the order. Well, indeed you can move English (UK) to the top, and with that make English (UK) the default instead, but then you can't successfully switch from English (US) directly to Avro Phonetic. (The position of "Bangla (Avro Phonetic)" doesn't matter in this case.)

The most sensible solution to this problem is to edit the XML file and hard code the layout you prefer.

So, as far as I understand, we have these choices:

1. Set "us" in the XML file and inform the users in line with what I wrote at the start of this thread.

2. Set "default" in the XML file and advise the users to edit it themselves in case of more than one XKB layout.

Possibly fewer users would stumble upon the issue with only latin letters in case of 2. The downside is that users with > 1 layout wouldn't be able to fix it via the GUI, but would need to edit a program file manually. Besides, that file is package owned, and the change would be overwritten when the package is updated.

As already stated in previous comments, my conclusion at this point is that 1. is preferable. But admittedly the choice is not obvious.

**Comment by AnwarShah** [comment] 2019-07-30 14:19
> I have personally tested and ibus-avro in its current state, works in all DE (gnome, kde, lxde etc..) where ibus is supported. The issues reported here are mostly user error, among those are,
> 
> 1. IBus is not properly configured in DE, ex: ibus gtk3/gtk2/qt immodule not installled, or GTK_IM_MODULE=ibus not set.
> 2. After installing ibus-avro, ibus daemon is not reloaded so ibus-avro is not showing up in input sources list. solution is to reload ibus-daemon manually or restart DE (gnome) session.

Though I didn't get the problem before, but I've tested it now and found that the issue is indeed present. I've set GTK_IM_MODULE to `ibus` and ibus-daemon is running. Simply changing the order does fix the issue too!

**Comment by AnwarShah** [comment] 2019-07-30 16:22
> The most sensible solution to this problem is to edit the XML file and hard code the layout you prefer.

If the user hardcode the layout file and then try to switch directly from a non-hardcoded layout to Avro, what will happen? 

The nature of the problem suggests that Avro tries to use the layout the user just switched from and get stuck somewhere.

**Comment by gunnarhj** [comment] 2019-07-30 16:45
> > The most sensible solution to this problem is to edit the XML file and hard code the layout you prefer.
> 
> If the user hardcode the layout file and then try to switch directly from a non-hardcoded layout to Avro, what will happen?

All XKB layouts are hardcoded (as opposed to IBus IMs which often have "default" instead). If you ask what happens if the user switches directly from some other layout than what he stated in the XML file of Avro Phonetic, we are back to where we started: The order matters. As long as Avro Phonetic (or the layout he stated in the XML file) is first in the list, it works. Please note that this is similar to the present choice, a hardcoded "us" layout value.

> The nature of the problem suggests that Avro tries to use the layout the user just switched from and get stuck somewhere.

Yep, that's what the "default" value might lead to.

**Comment by gunnarhj** [comment] 2019-07-30 21:49
@sarim: Some of the files in the repository, e.g. `avrodict.js` and `suffixdict.js`, are obviously generated somehow. I suppose that the `database-compiler.js` script has something to do with it.

The sponsor, who uploaded ibus-avro to Debian's NEW queue, advised me that it would be desirable, and increase the chance of approval, if the package source included a description of where the original sources are available and how those files can be regenerated. Is there such a description available anywhere?

**Comment by AnwarShah** [comment] 2019-07-31 01:42
@gunnarhj I think hardcoding `us` as the default and giving a notice while the package being installed via something like mscorefonts EULA notice would be fine. You can tell them if they are using more than 1 layout other than avro, then they need to check the README file for a possible solution if Bangla is not being inputted correctly.

**Comment by gunnarhj** [comment] 2019-07-31 09:17
> I think hardcoding `us` as the default

Good, then we are agreed on that.

> and giving a notice while the package being installed via something like mscorefonts EULA notice would be fine.

That's an interesting idea, @AnwarShah. Haven't thought about it, but will look into it.

> You can tell them if they are using more than 1 layout other than avro, then they need to check the README file for a possible solution if Bangla is not being inputted correctly.

I think you are mixing it up now. With "us" as layout, you may run into the issue even if you only have one layout besides Avro Phonetic, i.e. if the layout is something else but "English (US)".

**Comment by sarim** [comment] 2019-07-31 12:52
@gunnarhj Those come from a sqlite3 database, I have to search for the original database, don't exactly have its location memorized right now. I'll let you know.

**Comment by AnwarShah** [comment] 2019-07-31 19:31
> The downside is that users with > 1 layout wouldn't be able to fix it via the GUI, but would need to edit a program file manually

Then, I think `default` will be better. Because the switching would work even if a user don't have English US layout as default. 

> English (US) is default, since it's at the top of the list. If you switch from English (US) to Avro Phonetic, it works, but if you switch from English (UK) directly to Avro Phonetic, only latin letters are inputted. And you can't fix it by changing the order.

I think I can fix the problem by changing switching. I've just discovered that, if you can't input via Avro for this issue, You need to switch to the default layout first (the one at the top of the list). Then switch to the avro (even if it requires more than 1 tab key) . Then you can input Bangla again! Can you test this? 

Besides, I think avro tries to rank itself automatically to the top of the list. `<rank>0</rank>` was used in layout which i think is doing the job.

**Comment by gunnarhj** [comment] 2019-07-31 20:30
@sarim: I see. Can't tell how significant it is, but it's probably good if you make yourself prepared to explain if Debian's archive admins ask.

**Comment by gunnarhj** [comment] 2019-07-31 20:55
> > English (US) is default, since it's at the top of the list. If you switch from English (US) to Avro Phonetic, it works, but if you switch from English (UK) directly to Avro Phonetic, only latin letters are inputted. And you can't fix it by changing the order.
> 
> I think I can fix the problem by changing switching. I've just discovered that, if you can't input via Avro for this issue, You need to switch to the default layout first (the one at the top of the list). Then switch to the avro (even if it requires more than 1 tab key) . Then you can input Bangla again! Can you test this?

I have already tested it, and I can confirm that it works as you say, @AnwarShah. But personally I think that would cause more confusion than using "us".

- With "us" the user can fix it once right after having installed the program, and doesn't need to think about it afterwards. With "default" you'd likely stumble upon the issue repeatedly if you have more than one layout besides Avro Phonetic.

- Since a couple of years ago, "us" is the layout in the upstream code. I don't think it would be wise to publish a package with "default" which also comes with an issue, even if it manifests itself a bit differently. That would in itself create confusion among the users.

I'd also like to mention that I have fixed a prompt as you suggested, and which I thought was an excellent idea. I'm about to upload to a PPA, so you can see for yourself what it looks like.

> Besides, I think avro tries to rank itself automatically to the top of the list. `<rank>0</rank>` was used in layout which i think is doing the job.

I have tried to change the rank value, but as far as I was able to figure out, it didn't make a difference with respect to the issue we are trying to handle.

**Comment by gunnarhj** [comment] 2019-07-31 22:14
@sarim, @AnwarShah: It may take a while before a Debian decision is made, but in the meantime I hope to be able to have it uploaded to Ubuntu. This is the package I would like to upload:

https://launchpad.net/~gunnarhj/+archive/ubuntu/ibus-avro

That is, if not somebody objects loudly. ;)

Please install and let me know what you think. It includes a notification when the package is installed for the first time which prompts the user to study the README.Debian file.

**Comment by AnwarShah** [comment] 2019-08-01 00:32
I've installed it and liked the prompt. I think the prompt could be a bit more description on exactly when a user might have need this. Also, the prompt could be shown at the end of package installation instead of at start like the ones you get when you install more than 1 display manager to select a default.

**Comment by gunnarhj** [comment] 2019-08-01 01:21
> I think the prompt could be a bit more description on exactly when a user might have need this.

Ok. Any suggested wording?

Currently it reads as follows:

```
Heads-up for GNOME on Xorg (including Ubuntu on Xorg)

If you may use ibus-avro in GNOME sessions on Xorg (including
Ubuntu on Xorg), please study the file /usr/share/doc/ibus-avro/README.Debian
for important advice on the input source configuration.
```
My thinking was to focus on the desktop environment where it _**may**_ be a problem. So if you are on Kubuntu or Linux Mint or Debian with Cinnamon etc. (or GNOME on Wayland) you don't need to bother. Found it hard to be more precise without including basically everything in README. But I'm listening...

(The prompt is prepared for translations, btw, so if you like, I can send you a PO file so you can add a Bangla translation. That way the prompt would be shown in Bangla for users with a `bn_BD` or `bn_IN` locale.)

> Also, the prompt could be shown at the end of package installation instead of at start like the ones you get when you install more than 1 display manager to select a default.

That would make it technically more complicated. We only want the prompt to be shown at the first installation, not at upgrades, right? That is achieved naturally this way. And, after all, the completion of the installation doesn't take more than a couple of seconds, so is it really so important?

> > Since a couple of years ago, "us" is the layout in the upstream code. I don't think it would be wise to publish a package with "default" which also comes with an issue, even if it manifests itself a bit differently. That would in itself create confusion among the users.
> 
> "us" would be better then I think

I'm glad that you too come to that conclusion.

**Comment by AnwarShah** [comment] 2019-08-01 07:11
> Ok. Any suggested wording?

You can include when exactly that is required. Maybe 

```
Heads-up for GNOME on Xorg (including Ubuntu on Xorg)

If you are using ibus-avro in GNOME on Xorg session(including
Ubuntu on Xorg), please study the file /usr/share/doc/ibus-avro/README.Debian
for important advice on the input source configuration and possible fix if you encounter problem of 
not being Bangla characters being inputted.
```

> (The prompt is prepared for translations, btw, so if you like, I can send you a PO file so you can add a Bangla translation. That way the prompt would be shown in Bangla for users with a bn_BD or bn_IN locale.)

You can send it. 

> ...so is it really so important?

Not very important I think.

**Comment by gunnarhj** [comment] 2019-08-01 18:10
@AnwarShah: That's a good clarification of the prompt wording. Thanks! PO file sent.

@sarim: Any doubts from you before I ask a sponsor to upload to Ubuntu?

**Comment by sarim** [comment] 2019-08-01 20:20
Can we do something like the script checks a environment variable (I'm pretty sure there is one) to check if gnome is running on X or wayland, and only show the message to user if he's using gnome on xorg?

**Comment by gunnarhj** [comment] 2019-08-01 23:07
@sarim: I thought that sounded as a good idea, and the version currently in the PPA tries to do that. It checks the `XDG_CURRENT_DESKTOP` and `XDG_SESSION_TYPE` variables.

However, it doesn't work. Now the message is never shown, at least not in Ubuntu. The reason is that when you install a package you do it as superuser via e.g. the `sudo` command, and then those variables are not present in the environment.

The prompt is shown if you do a new install this way:

    sudo -E apt install ibus-avro

But how many users add that `-E` option when installing?

So unfortunately I don't know how it would be done.

Personally I don't think that users on other desktop environments who see the message will be so bothered by it. They simply note that it does not apply to them, press Enter, and move on.

**Comment by gunnarhj** [comment] 2019-08-01 23:28
Obviously it would be best if we could spot the root cause, fix the issue, and get rid of these warnings/instructions. But personally I don't even know where to start looking, and I suppose it would be a very time consuming exercise.

Also, the problem is transient. Once all distros ship GNOME on Wayland only, the problem ought to be history. But we are not there yet.

**Comment by rifat-H** [comment] 2019-08-02 02:29
before ibus-avro become available in repos.. please put the deb file on github. as a distrohopper i am too tired to install from source.

**Comment by gunnarhj** [comment] 2019-08-02 03:07
@rifat-H: As mentioned in the start of this thread, you can get a .deb file from [this PPA](https://launchpad.net/~gunnarhj/+archive/ubuntu/avro) in the meantime.

**Comment by AnwarShah** [comment] 2019-08-02 10:29
I think we should display the prompt in all cases. Because, user may install it in wayland and then can switch to xorg session.

**Comment by AnwarShah** [comment] 2019-08-02 10:30
> Obviously it would be best if we could spot the root cause, fix the issue, and get rid of these warnings/instructions. But personally I don't even know where to start looking, and I suppose it would be a very time consuming exercise.

I wonder if it worth the time

**Comment by gunnarhj** [comment] 2019-08-02 12:02
> I think we should display the prompt in all cases. Because, user may install it in wayland and then can switch to xorg session.

That's a valid point. Anyway, I have removed the broken code from the PPA, so now it's shown again.

P.S. Any chance you can fix that translation? Hopefully that's the last piece in the puzzle before the initial release in Ubuntu.

**Comment by AnwarShah** [comment] 2019-08-02 12:12
> P.S. Any chance you can fix that translation? Hopefully that's the last piece in the puzzle before the initial release in Ubuntu.

I've sent it

**Comment by sarim** [comment] 2019-08-02 12:31
@gunnarhj Can you wait another day? I've been a long time since i did a deep dive into ibus's source code, but from what i remember, i don't think this issue would be so complex to fix. I haven't had the time to look into this last few days, hopefully I'll check today.

**Comment by gunnarhj** [comment] 2019-08-02 12:47
@sarim: Absolutely. It would be splendid if you could fix it. So I'll hold it for a couple of days, at least.

(Actually I dived into one file in the IBus source recently. As a result IBus will convert the "bn" language code to "Bangla" instead of "Bengali" going forward.)

**Comment by sarim** [comment] 2019-08-02 13:34
> (Actually I dived into one file in the IBus source recently. As a result IBus will convert the "bn" language code to "Bangla" instead of "Bengali" going forward.)

Oh my god. Few years back i was pulling my hair for a whole night trying to figure out why avro is not showing up with others in "Bangla". What I found that time was that as both xkb-layouts and ibus-engines are shown together, both does the "bn" differently. As a result xkb "bn" layouts were going to "bangla" and ibus "bn" engines were going to "Bengali" :P I should've contacted fujiwara at that time, but can't remember why i didn't :| 

About the "us" layout issue, I'm opening a new thread for that discussion as i found some clues upstream.

**Comment by sarim** [comment] 2019-08-02 14:55
The issue should be fixed now. Please check :) @gunnarhj

**Comment by gunnarhj** [comment] 2019-08-02 15:21
Wow! Amazing!! I applied that commit as a patch for now, and uploaded it as `1.0+git20170418-0ubuntu1~ppa5` here:

https://launchpad.net/~gunnarhj/+archive/ubuntu/ibus-avro

Not tested yet, but will do, of course. (Haven't removed the prompt stuff yet either.)

Will be back later with my observations.

Btw, if this proves to be it, wouldn't that be worth to celebrate by releasing version 1.1? That would make the package's version number less cumbersome.

**Comment by gunnarhj** [comment] 2019-08-02 16:00
@sarim: Yep, a quick test here indicates that that commit fixed it. Now বাংলা can be inputted irrespective of how the input sources are ordered - also on GNOME on Xorg. Hopefully @AnwarShah can confirm it too.

Before I clean up the package from the (now) redundant stuff, what do you say about releasing 1.1?

**Comment by AnwarShah** [comment] 2019-08-02 16:04
Wow! This is great news actually! Thanks @sarim 

I'll test it soon and will inform here.

**Comment by AnwarShah** [comment] 2019-08-02 16:58
> @sarim: Yep, a quick test here indicates that that commit fixed it. Now বাংলা can be inputted irrespective of how the input sources are ordered - also on GNOME on Xorg. Hopefully @AnwarShah can confirm it too.
> 

Unfortunately, it's different here. If I order them as 
English (UK)
English (US)
Avro 

I can't input Bangla. If I make Avro at first or English (US) at first position, I can input Bangla.

The layout has `us` as default

**Comment by sarim** [comment] 2019-08-02 17:48
@gunnarhj I know there another bug, (not related to the issue we're discussing here), it is rare and there is a easy work around so i was ignoring it for now, but If i release 1.1, i'd prefer to patch that too in it. Lets see i can do that quickly.

**Comment by gunnarhj** [comment] 2019-08-02 22:03
@sarim: Ok. That version number aspect is really not important; it was rather a thought. If you fix that bug and release very soon, I'll use the new release tarball as upstream. Otherwise I think that what's now in [the PPA](https://launchpad.net/~gunnarhj/+archive/ubuntu/ibus-avro) is quite ok to publish in Ubuntu. The ugly issue gone (unless Anwar proves otherwise), no prompt or README.

I have now tested on Ubuntu 19.04, Ubuntu 19.10, and Debian with GNOME (Xorg). I simply cannot make it fail any longer.

@AnwarShah: Can't help wondering if you missed something simple. Did you apply Sarim's patch yourself, or did you install from one of my PPAs? If the latter, which version of the package have you installed?

    dpkg-query -W *avro

Also, did you relogin after having updated Avro Phonetic?

Really hoping that we finally find that it works for you too.

**Comment by AnwarShah** [comment] 2019-08-03 01:43
@gunnarhj  

`dpkg-query -W *avro` returns `avro	2.1-9~18.04`. I've updated avro from the ppa and tested. Didn't you have the ppa too? I've seen another update. Let me re-check

**Comment by AnwarShah** [comment] 2019-08-03 01:48
Oops! I see you didn't update the code in 2.1-9. I've updated to `2.1-10` and re-login. It seems the problem has really gone!

**Comment by gunnarhj** [comment] 2019-08-03 04:49
Yay! :+1: 

Yeah, there are two PPAs. [One for providing it to users](https://launchpad.net/~gunnarhj/+archive/ubuntu/avro) (via the `avro` package) until it's in Ubuntu's official repos, and [one with the exact source](https://launchpad.net/~gunnarhj/+archive/ubuntu/ibus-avro) which I will ask a sponsor to upload to Ubuntu eoan. The former had not yet been updated when you tested yesterday. My first test yesterday was via the latter. Sorry for the confusion.

**Comment by gunnarhj** [comment] 2019-08-03 05:49
@sarim: Then only one question remains: Should what we have now be uploaded, or should I wait for 1.1? I'm inclined to give the sponsor a green light now for `ibus-avro 1.0+git20170418-0ubuntu1` in order to keep the ball rolling. Then we'll faster get the name space established, and I can start getting it in (as backports) also in the stable supported releases (19.04, 18.04, 16.04). A few persons will be involved before that has been completed.

The initial release is just that, meaning that when you release 1.1 I will upgrade in the Ubuntu archive too.

Is that a reasonable plan? Or do you already have yet another one liner under way for the other bug? ;)

**Comment by sarim** [comment] 2019-08-03 16:28
> Is that a reasonable plan? Or do you already have yet another one liner under way for the other bug? ;)
I already pushed the commit. I'll test a bit more and release v1.1 in few hours :)

**Comment by gunnarhj** [comment] 2019-08-03 16:47
A few hours is not long. Then I'm going to wait for 1.1, of course.

**Comment by sarim** [comment] 2019-08-03 20:07
v1.1 is released

**Comment by sarim** [comment] 2019-08-04 13:36
Okey last night's v1.1 was kinda borked :| I pushed the tag from mobile (didn't have power and internet due to street construction work from city). I realized today that i forgot to change the version in xml. I updated it today and re-released v1.1 :| what a mess. So sorry :(  

@gunnarhj If you already uploaded the build, please do again.

**Comment by gunnarhj** [comment] 2019-08-04 15:30
@sarim: N.p. Still only [in PPA](https://launchpad.net/~gunnarhj/+archive/ubuntu/ibus-avro). Updated.

**Comment by sarim** [comment] 2019-08-04 15:50
+1 
Off topic, I found a potential issue in gnome-control-center while testing avro. Opened an issue in gnome gitlab.

**Comment by gunnarhj** [comment] 2019-08-04 16:44
@sarim: Good catch. gnome-control-center is kind of ... GNOME centric. I see that the issue affects ibus-mozc too.

On a similar (off) topic: The package adds an AppStream metadata file. Hopefully it will make Avro Phonetic visible in and installable from Ubuntu Software and other modern software managers. But such a file would really fit better in the upstream source. Even if it doesn't matter currently, you may want to consider to 'take over' it, so it's there if Avro Phonetic gets packaged as e.g. .rpm, snap or flatpak.

**Comment by sarim** [comment] 2019-08-04 17:50
AppStream, hmmm, haven't heard the name before. Googled it. What happened to snap? People thought it was going to be the final answer to packages for everyone :P I personally don't like them :P 

Does AppStream places apps in containers like snap? Last time i looked at snap, i came to the conclusion that ibus-avro can't be used inside containers like that, as it requires communication with ibus which is running outside the container. Nevertheless, I'll look at this later, I'll be out of town for next couple of weeks, I'll check after i return.

**Comment by gunnarhj** [comment] 2019-08-04 18:03
AppStream isn't related to snap. It's a universal protocol for providing meta info about applications. This is what the file I was talking about looks like:

    <?xml version="1.0" encoding="UTF-8"?>
    <component type="inputmethod">
      <id>com.github.sarim.ibus.avro</id>
      <metadata_license>CC0-1.0</metadata_license>
      <name>Avro Phonetic</name>
      <summary>IBus engine for Avro Phonetic</summary>
      <description>
        <p>
          ibus-avro is a port of the popular Avro Phonetic Bangla typing method
          to Linux. This software works as an Engine (plugin) of IBus and lets
          users type in English and on-the-fly transliterate them phonetically
          to Bangla.
        </p>
      </description>
      <url type="homepage">https://github.com/sarim/ibus-avro</url>
      <developer_name>Sarim Khan</developer_name>
      <project_license>MPL-1.1</project_license>
    </component>

But this is indeed no urgency. Let's talk about it later.

**Comment by gunnarhj** [comment] 2019-08-16 19:37
`ibus-avro` is now an official package in both [Debian](https://packages.debian.org/sid/ibus-avro) and [Ubuntu](https://launchpad.net/ubuntu/+source/ibus-avro). In Debian it's only in `sid/unstable` so far, but in a few days it will probably be migrated to `bullseye/testing`. In Ubuntu it's available in all the supported versions (16.04, 18.04, 19.04) as well as the current development version.

So on Ubuntu or Debian sid, to install `ibus-avro`:

    sudo apt install ibus-avro

On Ubuntu 19.10 you can find and install `ibus-avro` via Ubuntu Software (i.e. Ubuntu's variant of GNOME Software).

![software](https://user-images.githubusercontent.com/7826045/63190547-ba853500-c066-11e9-8179-f691085fa86f.png)

I don't know yet to which extent this GUI way will work in the supported Ubuntu releases. Possibly the fact that they are in the `backports` pockets there is a problem. Time will tell. But to the extent it works, it's kind of cool that the users can install and enable the input method without a need to open a terminal window.

There are some minor things I'd like to bring up for discussion as a follow-up of this, but I will do so later in a separate issue.

However, before closing this issue, there is one important thing left: The users of APT based Linux systems should be informed somehow. The first thing in my mind is that the `README.md` file should probably be updated to reflect the presence of `ibus-avro` in Debian/Ubuntu. Users on those systems should no longer need to struggle with dependencies and building from the git repo.

[OmicronLab's Linux pages](https://linux.omicronlab.com/) need a big overhaul too, of course.

It would also be good if @maateen could start to redirect his avro project at GitHub to this project. The `.deb` files he prepared and makes available were indeed useful previously, and have most certainly contributed to spread `ibus-avro` to a wider audience. However, since maateen's avro project is in read-only mode, while a couple of new issues showed up, those `.deb` files may now contradict the purpose.

Those are my thoughts for now. I take it that you who are native speakers have other ideas how to spread the word to current and potential Linux users.

**Comment by gunnarhj** [comment] 2019-08-16 23:21
> I don't know yet to which extent this GUI way will work in the supported Ubuntu releases. Possibly the fact that they are in the `backports` pockets there is a problem. Time will tell.

Correction: The GUI way works in all Ubuntu versions. As from Ubuntu 18.04 you can, besides entering a search term to find Avro Phonetic, navigate via _Add-ons_ -> _Input Sources_ to find it.

**Comment by AnwarShah** [comment] 2019-08-17 09:50
> `ibus-avro` is now an official package in both [Debian](https://packages.debian.org/sid/ibus-avro) and [Ubuntu](https://launchpad.net/ubuntu/+source/ibus-avro). In Debian it's only in `sid/unstable` so far, but in a few days it will probably be migrated to `bullseye/testing`. In Ubuntu it's available in all the supported versions (16.04, 18.04, 19.04) as well as the current development version.
> 
> So on Ubuntu or Debian sid, to install `ibus-avro`:
> 
> ```
> sudo apt install ibus-avro
> ```
> 

Nice to hear the news. It's on bionic-backports in 18.04 and just installed it.

**Comment by gunnarhj** [comment] 2019-08-17 18:01
> Nice to hear the news. It's on bionic-backports in 18.04 and just installed it.

And it's nice to hear such feedback from someone who is actually using the thing.

**Comment by maateen** [comment] 2019-08-19 05:37
> It would also be good if @maateen could start to redirect his avro project at GitHub to this project. The .deb files he prepared and makes available were indeed useful previously, and have most certainly contributed to spread ibus-avro to a wider audience. However, since maateen's avro project is in read-only mode, while a couple of new issues showed up, those .deb files may now contradict the purpose.

@gunnarhj Thanks a lot for your contribution to Avro Project. I completely agree with you. The `.deb` packages we made is no longer valid. I will lift and shift the things (if there is any) to this project soon. @sarim bhai, please help me on this.

Also, sorry for making that repo read-only. I could no longer maintain the `.deb` packages.

**Comment by gunnarhj** [comment] 2019-08-19 13:54
Thanks for *your* contribution, @maateen. Your project inspired me to take it a step further and establish official Debian/Ubuntu packages. Actually I used your packages as a starting point a couple of months ago.

**Comment by sarim** [comment] 2019-08-19 14:12
@maateen Sure bro, what do you need?
At the start, I had both deb and rpm build system running in obs, but over the years got busy and didn't had time to maintain....

I'll start on editing the linux.omicronlab.com website.

btw, It seems like icon and screenshots are missing from appstream metadata and [package list](https://packages.ubuntu.com/eoan/ibus-avro) page, appstream docs has icon and screenshots field, lets see if i can make it work :P

**Comment by gunnarhj** [comment] 2019-08-19 14:37
> btw, It seems like icon and screenshots are missing from appstream metadata and [package list](https://packages.ubuntu.com/eoan/ibus-avro) page, appstream docs has icon and screenshots field, lets see if i can make it work :P

I think that `icon` is mostly for GUI applications, and not for add-ons like [input methods](https://www.freedesktop.org/software/appstream/docs/sect-Metadata-InputMethod.html). But a screenshot would be a nice addition. If I understand it correctly, a screenshot would need to be [provided via a URL](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-screenshots) rather than included in the package.

**Comment by gunnarhj** [comment] 2019-08-19 15:00
@maateen: An idea:

How about first delete the whole project and then recreate it with only a `README.md` file, where you let the users know that it's closed - maybe together with some history - and refer them to this project.

**Comment by AnwarShah** [comment] 2019-08-19 18:45
@gunnarhj Just to inform you. You've used `NoDisplay=true` in the Avro preference .desktop file which would make the preference window hidden in menus. You should use `NoDisplay=false` instead I think

**Comment by gunnarhj** [comment] 2019-08-19 19:39
> You've used NoDisplay=true in the Avro preference .desktop file which would make the preference window hidden in menus.

@AnwarShah: That's true. But the only reason why I proposed that file was to make it possible to launch the preferences window from gnome-control-center, i.e. as a workaround of [this issue](https://gitlab.gnome.org/GNOME/gnome-control-center/issues/630) which Sarim submitted, and the file does serve that purpose also with `NoDisplay=true`.

Would it help to be able to access the preferences window from general desktop menus? I assumed not, since you can access it from the input source menu when Avro is selected (and from gnome-control-center, if you are on a desktop which has that). As far as I know, most other input method packages are not shown in general desktop menus (with Mozc as an exception).

**Comment by sarim** [comment] 2019-08-19 19:42
I prefer it hidden, no need to clutter user's app drawer (or what is it called in gnome :P ) As there is already two other options to launch the preferences.

**Comment by AnwarShah** [comment] 2019-08-20 07:32
Then, it's ok. I thought you wanted to show it but forgot to use NoDisplay=false. Otherwise I couldn't find a reason why it was required. Didn't test the file on GNOME. I used to use preference option from layout menu after switching to bn

**Closed** 2019-08-21 11:56 UTC
